#!/usr/bin/env groovy

library identifier: 'jenkins-shared-library@master', retriever: modernSCM(
    [
        $class: 'GitSCMSource',
        remote: 'https://github.com/dilafar/jenkins-shared-library.git',
        credentialsId: 'github-credentials'
    ]
)

def gv

pipeline{
    agent any

    tools {
        maven 'Maven'
    }
    environment {
        ANSIBLE_SERVER = "167.99.136.133"
    }

    stages{
        stage("increment version"){
            steps {
                script {
                    echo 'incrementing app version...'
                    incrementPatchVersion()
                    def matcher = readFile('pom.xml') =~ '<version>(.+)</version>'
                    def version = matcher[0][1]
                    env.IMAGE_NAME = "$version-$BUILD_NUMBER"
                }
            }
        }

        stage("build jar"){
            steps {
                script {
                    buildApp()
                }
            }
        }
        stage("test"){
            steps {
               script {
                    testApp()
               }
            }
        }
        stage("build image"){
            steps {
                script {
                    buildImage("dilafar/demo-app:$IMAGE_NAME")
                    dockerLogin()
                    dockerPush("dilafar/demo-app:$IMAGE_NAME")
                }
            }
        }
        stage("provision server"){
            environment {
                AWS_ACCESS_KEY_ID = credentials('jenkins_aws_access_key_id')
                AWS_SECRET_ACCESS_KEY = credentials('jenkins_aws_secret_access_key')
                TF_VAR_env_prefix = 'test'
            }
            steps {
                script {
                    dir('terraform'){
                        sh "terraform init"
                        sh "terraform fmt"
                        sh "terraform validate"
                        sh "terraform apply --auto-approve"
                        EC2_PUBLIC_IP = sh(
                            script: "terraform output ec2_public_ip",
                            returnStdout: true
                        ).trim()
                    }
                }
            }
        }
        stage("copy file to ansible server") {
            steps {
                script {
                        echo "copying all neccessary files to ansible control node"
                        sshagent(['ansible-server-key']){
                            sh "scp -o StrictHostKeyChecking=no ansible/* root@${ANSIBLE_SERVER}:/root"
                            withCredentials([sshUserPrivateKey(credentialsId: 'ec2-server-key', keyFileVariable: 'keyfile', usernameVariable: 'user')]){
                                sh 'scp $keyfile root@$ANSIBLE_SERVER:/root/ssh-key.pem'
                            }
                        }
                }
            }
        }
        stage("execute ansible playbook") {
            steps {
                script {
                    echo "calling ansible playbook to configure ec2 instance"
                    def remote = [:]
                    remote.name = "ansible-server"
                    remote.host = env.ANSIBLE_SERVER
                    remote.allowAnyHosts = true 

                   withCredentials([sshUserPrivateKey(credentialsId: 'ansible-server-key', keyFileVariable: 'keyfile', usernameVariable: 'user')]){
                        remote.user = user
                        remote.identityFile = keyfile
                        sshCommand remote: remote, script: "ansible-playbook install-docker-user.yml"
                        sshCommand remote: remote, command: "ansible-playbook install-docker-user.yml"
                    }
                }
            }
        }
        stage("deploy"){
            environment {
                DOCKER_CREDS = credentials('docker-hub-repo')
            }
            steps {
                script {
                    echo "waiting for EC2 server to initialize"
                    sleep(time: 90, unit: "SECONDS")
                    echo 'deploying docker image to EC2...'
                    echo "${EC2_PUBLIC_IP}"
                    def shellCmd = "bash ./commands.sh ${IMAGE_NAME} ${DOCKER_CREDS_USR} ${DOCKER_CREDS_PSW}"
                    sshagent(['ec2-server-key']) {
                        sh "scp commands.sh ec2-user@${EC2_PUBLIC_IP}:/home/ec2-user"
                        sh "scp docker-compose.yml ec2-user@${EC2_PUBLIC_IP}:/home/ec2-user"
                        sh "ssh -o StrictHostKeyChecking=no ec2-user@${EC2_PUBLIC_IP} ${shellCmd}"
                   }
                }
            }
        }
    }
}