#!/usr/bin/env groovy

library identifier: 'jenkins-shared-library@master', retriever: modernSCM(
    [
        $class: 'GitSCMSource',
        remote: 'https://github.com/dilafar/jenkins-shared-library.git',
        credentialsId: 'github-credentials'
    ]
)

def gv

pipeline{
    agent any

    tools {
        maven 'Maven'
    }

    stages{
        stage("increment version"){
            steps{
                script{
                    echo 'incrementing app version...'
                    incrementPatchVersion()
                    def matcher = readFile('pom.xml') =~ '<version>(.+)</version>'
                    def version = matcher[0][1]
                    env.IMAGE_NAME = "$version-$BUILD_NUMBER"
                }
            }
        }

        stage("build jar"){
            steps{
                script {
                    buildApp()
                }
            }
        }
        stage("test"){
            steps{
               script {
                    testApp()
               }
            }
        }
        stage("build image"){
            steps{
                script {
                    buildImage("dilafar/demo-app:$IMAGE_NAME")
                    dockerLogin()
                    dockerPush("dilafar/demo-app:$IMAGE_NAME")
                }
            }
        }
        stage("deploy"){
            steps{
                script {
                    deployApp()
                }
            }
        }
    }
}