#!/usr/bin/env groovy

library identifier: 'jenkins-shared-library@master', retriever: modernSCM(
    [
        $class: 'GitSCMSource',
        remote: 'https://github.com/dilafar/jenkins-shared-library.git',
        credentialsId: 'github-credentials'
    ]
)

def gv

pipeline{
    agent any

    tools {
        maven 'Maven'
    }

    stages{

        stage("build jar"){
            steps{
                script {
                    buildApp()
                }
            }
        }
        stage("test"){
            steps{
               script {
                    testApp()
               }
            }
        }
        stage("build image"){
            steps{
                script {
                    buildImage('dilafar/demo-app:jma-3.0')
                    dockerLogin()
                    dockerPush('dilafar/demo-app:jma-3.0')
                }
            }
        }
        stage("deploy"){
            steps{
                script {
                    deployApp()
                }
            }
        }
    }
}