---
- name: Install Docker, Docker Compose, and Start Docker Service
  hosts: tag_docker_server
  become: yes
  tasks:
    - name: Update cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - python3-pip
          - acl
        state: present

    - name: Install specific version of Docker SDK for Python
      pip:
        name:
          - docker
          - docker-compose

  roles:
    - install_docker
    - install_docker_compose
    - start_docker